from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field


class MsgIn(BaseModel):
    """A single conversation turn sent from the client or used internally.

    Attributes:
        role: ``"user"`` or ``"assistant"``.
        content: Text content of the turn.
    """

    role: Literal["user", "assistant"]
    content: str


class WsIncoming(BaseModel):
    """Validated shape of every JSON frame sent by the WebSocket client.

    Attributes:
        type: ``"message"`` for a chat turn; ``"ping"`` for a keepalive.
        conversation_id: Existing conversation to resume, or empty string to start a new one.
        messages: Ordered conversation history with the latest message last.
        model: Model identifier override; empty string uses the session-stored or default model.
        temperature: Sampling temperature forwarded to the provider (0.0–2.0).
    """

    type: Literal["message", "ping"]
    conversation_id: str = ""
    messages: list[MsgIn] = Field(default_factory=list)
    model: str = ""
    temperature: float = Field(default=0.7, ge=0.0, le=2.0)


# ── outgoing frames ──────────────────────────────────────────────────────────

class WsDelta(BaseModel):
    """Streaming token frame sent during freeform LLM output.

    Attributes:
        content: Single token or partial token string from the provider stream.
    """

    type: Literal["delta"] = "delta"
    content: str


class WsDone(BaseModel):
    """End-of-stream frame for freeform (non-agent) responses.

    Attributes:
        conversation_id: UUID of the conversation this turn belongs to.
        token_count: Estimated token count (``len(content) // 4``).
        provider: Provider name that generated the response.
        model: Model identifier used for this turn.
    """

    type: Literal["done"] = "done"
    conversation_id: str
    token_count: int
    provider: str
    model: str


class WsError(BaseModel):
    """Error frame sent when a recoverable error occurs mid-turn.

    The WebSocket connection remains open after an error frame; the client
    should display the error message and allow the user to retry.

    Attributes:
        message: Human-readable error description.
        code: HTTP-style status code (e.g. ``500``).
    """

    type: Literal["error"] = "error"
    message: str
    code: int


class WsPong(BaseModel):
    """Keepalive reply frame sent in response to a ``ping``."""

    type: Literal["pong"] = "pong"


class WsTitle(BaseModel):
    """Async frame carrying the auto-generated conversation title.

    Sent after the first message in a new conversation, asynchronously
    after the main response frame, once the title generation completes.

    Attributes:
        conversation_id: UUID of the conversation whose title was set.
        title: Short 4-word title generated by the LLM.
    """

    type: Literal["title"] = "title"
    conversation_id: str
    title: str


class WsProviderInfo(BaseModel):
    """Metadata for a single registered LLM provider.

    Attributes:
        provider: Provider name key (e.g. ``"anthropic"``).
        models: All model identifiers available under this provider.
        default_model: The model used when no override is specified.
    """

    provider: str
    models: list[str]
    default_model: str


class WsProviders(BaseModel):
    """Frame sent immediately on WebSocket connect listing all available providers.

    Attributes:
        data: List of provider metadata objects, one per registered provider.
    """

    type: Literal["providers"] = "providers"
    data: list[WsProviderInfo]


# ── agent frames (data query responses) ──────────────────────────────────────

class WsAgentProgress(BaseModel):
    """Progress notification sent during agent loop execution.

    Attributes:
        step: Machine-readable step identifier (e.g. ``"tool_call"``).
        message: Human-readable progress description shown to the user.
    """

    type: Literal["agent_progress"] = "agent_progress"
    step: str
    message: str


class WsClarificationRequest(BaseModel):
    """Clarification question frame sent when the agent cannot determine intent.

    The WebSocket loop pauses until the user replies. The reply is routed
    back as the clarification answer rather than a new question.

    Attributes:
        message: The clarifying question to present to the user.
        candidates: Optional list of intent labels to display as selectable options.
    """

    type: Literal["clarification_request"] = "clarification_request"
    message: str
    candidates: list[str] = Field(default_factory=list)


class WsAgentResponse(BaseModel):
    """Final structured response from the database agent loop.

    Sent in place of a ``done`` frame when the message was handled by
    ``run_agent_loop()`` rather than the freeform stream path.

    Attributes:
        conversation_id: UUID of the conversation this turn belongs to.
        explanation: LLM-generated natural-language explanation of the results.
        table_md: GitHub-flavoured markdown table of the result (max 50 display rows).
        csv: Full CSV export of the result DataFrame (all rows up to ``MAX_DATAFRAME_ROWS``).
        sql_used: Ordered list of SQL queries executed during the agent loop.
        python_used: Python code used for DataFrame merge operations, if any.
        truncated: ``True`` if results were capped at ``MAX_DATAFRAME_ROWS``.
        row_count: Total row count before any display truncation.
        provider: Provider name that executed the loop.
        model: Model identifier used for this turn.
    """

    type: Literal["agent_response"] = "agent_response"
    conversation_id: str
    explanation: str
    table_md: str
    csv: str
    sql_used: list[str] = Field(default_factory=list)
    python_used: str = ""
    truncated: bool = False
    row_count: int = 0
    provider: str
    model: str
