#!/usr/bin/env python3
"""probe_comms.py — generated by stress-test-fullstack skill.
Run from project root: python3 stress-test-report/probe_comms.py
Requires: httpx, docker running, stack up.
"""
from __future__ import annotations

import asyncio
import subprocess
import sys

try:
    import httpx
except ImportError:
    print("ERROR: httpx not installed. Run: pip install httpx")
    sys.exit(1)

results: list[dict] = []


def record(link: str, ok: bool, detail: str = "") -> None:
    icon = "PASS" if ok else "FAIL"
    results.append({"link": link, "ok": ok, "detail": detail})
    print(f"{icon}  {link}  {detail[:80]}")


def exec_in_backend(cmd: str) -> subprocess.CompletedProcess:
    backend_id = (
        subprocess.check_output(
            "docker ps --filter name=backend -q", shell=True
        )
        .decode()
        .strip()
        .split()[0]
    )
    return subprocess.run(
        ["docker", "exec", backend_id, "python3", "-c", cmd],
        capture_output=True,
        text=True,
        timeout=15,
    )


async def run() -> None:
    print("=== Communication Matrix ===")

    # Check Docker
    check = subprocess.run(["docker", "info"], capture_output=True, timeout=5)
    if check.returncode != 0:
        print("CRITICAL: Docker not running. Cannot probe live communication links.")
        sys.exit(1)

    async with httpx.AsyncClient(verify=False, timeout=10) as c:
        # 1. Browser → Nginx HTTP redirect
        r = await c.get("http://localhost/", follow_redirects=False)
        record("Browser→Nginx HTTP→HTTPS redirect", r.status_code in (301, 302), str(r.status_code))

        # 2. Browser → Nginx HTTPS root
        r = await c.get("https://localhost/", follow_redirects=True)
        record("Browser→Nginx HTTPS /", r.status_code == 200, str(r.status_code))

        # 3. Angular deep link (SPA routing)
        r = await c.get("https://localhost/conversations", follow_redirects=True)
        record("Angular SPA deep link", r.status_code == 200, str(r.status_code))

        # 4. Nginx → FastAPI health proxy
        r = await c.get("https://localhost/health")
        record("Nginx→FastAPI /health", "status" in r.text, r.text[:60])

        # 5. Auth endpoint
        r = await c.post("https://localhost/auth/guest")
        record("Angular→FastAPI POST /auth/guest", r.status_code == 200 and "access_token" in r.text, r.text[:60])

        # 6. Conversations endpoint (expects 401 without token)
        r = await c.get("https://localhost/api/conversations")
        record("Angular→FastAPI GET /api/conversations", r.status_code in (200, 401, 403), str(r.status_code))

    # 7. FastAPI → SQLite
    res = exec_in_backend(
        "import asyncio,aiosqlite; asyncio.run(aiosqlite.connect('data/chatbot.db'))"
    )
    record("FastAPI→SQLite", res.returncode == 0, res.stderr[:80])

    # 8. FastAPI → Redis (if REDIS_ENABLED)
    res = exec_in_backend(
        "import os; enabled=os.environ.get('REDIS_ENABLED','false').lower(); "
        "print('disabled' if enabled!='true' else 'checking'); "
        "import asyncio,redis.asyncio as r; "
        "asyncio.run(r.from_url(os.environ.get('REDIS_URL','redis://redis:6379/0')).ping()) if enabled=='true' else None"
    )
    if "disabled" in (res.stdout + res.stderr):
        record("FastAPI→Redis", True, "REDIS_ENABLED=false (in-memory fallback, expected)")
    else:
        record("FastAPI→Redis", res.returncode == 0, res.stderr[:80])

    # 9. WebSocket route reachable (just HTTP handshake check)
    try:
        proc = subprocess.run(
            ["curl", "-sk", "-I", "--max-time", "3",
             "-H", "Upgrade: websocket",
             "-H", "Connection: Upgrade",
             "https://localhost/ws/"],
            capture_output=True, text=True, timeout=8
        )
        ok = any(c in proc.stdout for c in ["101", "400", "426"])
        record("Nginx WS route /ws/", ok, proc.stdout.split("\n")[0][:80])
    except Exception as e:
        record("Nginx WS route /ws/", False, str(e)[:80])

    broken = [r for r in results if not r["ok"]]
    print(f"\nComms: {len(results) - len(broken)}/{len(results)} links OK")
    if broken:
        print("P0 broken links:")
        for b in broken:
            print(f"  FAIL  {b['link']}: {b['detail']}")
        sys.exit(1)
    else:
        print("All communication links PASSED")


if __name__ == "__main__":
    asyncio.run(run())
