#!/usr/bin/env bash
# probe_hosting.sh — generated by stress-test-fullstack skill
# Run from project root: bash stress-test-report/probe_hosting.sh
set -euo pipefail
PASS=0; FAIL=0; SKIP=0

probe() {
  local name="$1" cmd="$2" expect="$3"
  result=$(eval "$cmd" 2>&1) || true
  if echo "$result" | grep -q "$expect"; then
    echo "PASS  $name"
    ((PASS++))
  else
    echo "FAIL  $name  =>  ${result:0:120}"
    ((FAIL++))
  fi
}

skip() {
  echo "SKIP  $1  (reason: $2)"
  ((SKIP++))
}

echo "=== Hosting Probes ==="

# Check Docker is running first
if ! docker info >/dev/null 2>&1; then
  echo ""
  echo "CRITICAL: Docker daemon is not running."
  echo "Start Docker Desktop (Mac) or 'sudo systemctl start docker' (Linux), then re-run."
  echo ""
  echo "To start the stack: cd chatbot && docker compose up -d --build"
  exit 1
fi

# Check services are up
if ! docker compose -f chatbot/docker-compose.yml ps --services --filter status=running 2>/dev/null | grep -q "nginx"; then
  echo "Services not running. Starting stack..."
  (cd chatbot && docker compose up -d) || { echo "FAIL: docker compose up failed"; exit 1; }
  echo "Waiting 30s for services to become healthy..."
  sleep 30
fi

probe "HTTP→HTTPS redirect"   "curl -sI http://localhost/ | head -1"                      "301\|302"
probe "Angular root 200"       "curl -sk https://localhost/ | head -c 50"                  "html\|doctype\|DOCTYPE\|<app"
probe "Angular deep link 200"  "curl -skI https://localhost/conversations | head -1"       "200"
probe "Nginx health passthrough" "curl -sk https://localhost/health"                       '"status"'
probe "FastAPI /api/ 200"      "curl -skI https://localhost/api/conversations | head -1"   "200\|401"
probe "No 502 on /api"         "curl -skI https://localhost/api/conversations | head -1"   "200\|401\|403"
probe "Auth guest endpoint"    "curl -sk -X POST https://localhost/auth/guest"             '"access_token"'
probe "TLS cert present"       "curl -vk https://localhost/ 2>&1"                         "SSL\|TLS\|certificate"
probe "WS route reachable"     "curl -skI https://localhost/ws/ | head -1"                 "101\|400\|426"

# Internal connectivity probe (requires docker exec)
BACKEND_ID=$(docker ps --filter name=backend -q 2>/dev/null | head -1)
if [ -n "$BACKEND_ID" ]; then
  probe "FastAPI internal health" \
    "docker exec $BACKEND_ID curl -sf http://localhost:8080/health" \
    '"status"'
  probe "FastAPI→Redis" \
    "docker exec $BACKEND_ID python3 -c 'import asyncio,redis.asyncio as r,os; asyncio.run(r.from_url(os.environ.get(\"REDIS_URL\",\"redis://redis:6379/0\")).ping())'" \
    "True\|PONG\|b'True'"
else
  skip "FastAPI internal health" "backend container not found"
  skip "FastAPI→Redis" "backend container not found"
fi

echo ""
echo "Hosting: $PASS passed / $((PASS+FAIL+SKIP)) total ($SKIP skipped)"
[ "$FAIL" -eq 0 ] || { echo "HOSTING BLOCKED — $FAIL failure(s) require fixes before Phase 2"; exit 1; }
echo "All hosting probes PASSED"
